### ISSUE TITLE
How to create `dll` for `libgit2`

### ISSUE THREAD

**Issue by nivekithan** [dart-lang/ffi#102]
I am trying to create bindings for [`libgit2`](https://github.com/libgit2/libgit2) using `ffigen`. I followed the [steps mentioned here](https://github.com/dart-lang/ffigen/issues/213#issuecomment-839631996). 

Now to use those bindings I have to create `dll` in windows. This is where I am getting stuck. I have both `cmake` and `make` in my `PATH`.  I have also created a question on [stackoverflow](https://stackoverflow.com/questions/67505823/cmake-is-not-making-makefile?noredirect=1#comment119322819_67505823). But I didnt really get any solution.

You can check my [repo online](https://github.com/nivekithan/git2dart) or you can clone it using `gh repo clone nivekithan/git2dart`. 

In my repo there will directory called `lib2git` where I have pasted the contents of `include` directory of [libgit2](https://github.com/libgit2/libgit2) ( it only contains `.h` files not `.c` files) and also there will be `CMakeLists.txt` with the following config

```cmake
cmake_minimum_required(VERSION 3.20.2 FATAL_ERROR)
project(libgit VERSION 1.0.0 LANGUAGES C)
add_library(libgit SHARED git2.h)

set_target_properties(libgit PROPERTIES
    PUBLIC_HEADER git2dart.h
    VERSION {PROJECT_VERSION}
    SOVERSION 1
    LINKER_LANGUAGE C
    OUTPUT_NAME "git2dart"
)
```
so passing the command `cmake .`,  gives me this output

```
 Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.21376.
-- The C compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/nivek/Documents/work/git2dart/libgit2
```

Then passing the command `make` is giving me this output

```
make: *** No targets specified and no makefile found.  Stop.
```

So what I am supposed to do on creating `dll` file?

Thanks for the help

**Comment by dcharkes** [comment]
The default on Windows is that CMake generates a Visual studio project, not a CMake project.

`cmake --build .` will automatically run the build as well if visual studio is available on your machine.

Alternatively, you could tell CMake to generate a make file instead of visual studio project.
