### ISSUE TITLE
Wide characters

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/ffi#111]
I need to decode wide character (`wchar_t`) strings. The size of `wchar_t` can vary between platforms; on Windows, for example, it's 2 bytes (UTF-16) , but on macOS, it's 4 (UTF-32).

At the moment, there's no easy way to decode these characters properly. It's be great if something like a `WChar` type was created, and there was a function on `Pointer<WChar>` to generate a string.

**Comment by dcharkes** [comment]
This is tracked in https://github.com/dart-lang/sdk/issues/42563.

**Comment by hacker1024** [comment]
https://github.com/dart-lang/sdk/issues/42563 covers the `wchar_t` type representation in Dart, but once this is resolved, a utility function to handle string conversions should still be implemented in `package:ffi`. Can this issue stay open?
