### ISSUE TITLE
Pointer of A Pointer Issue

### ISSUE THREAD

**Issue by GZGavinZhao** [dart-lang/ffi#125]
I know this is not supposed to be a help forum, but I've been scratching my head around this for a week and have no idea why this happened.

I'm creating a Dart wrapper for [libgit2](https://github.com/libgit2/libgit2). The C api for `git_repository_init` is `int git_repository_init(git_repository **out, const char *path, unsigned int is_bare);`. According to the [official docs](https://libgit2.org/docs/guides/101-samples/), you init a repository by doing some like this:
```c
git_repository *repo = NULL;
int error = git_repository_init(&repo, "/tmp/…", false);
```

The problem is that the parameter `out` is a pointer of a pointer. In Dart, I can't get the printer of a pointer directly, so I achieve it through this:
```dart
final Pointer<git_repository> repo = nullptr;
int error = libgit.git_repository_init(
  Pointer.fromAddress(repo.address),
  location,
  0,
);
```
However, libgit2 returns me with the error: `message: invalid argument: 'out'`.

Meanwhile, for another function, ` int git_repository_open(git_repository **out, const char *path); ` also uses "double pointer", and calling that function doesn't cause any problems...
```dart
int error = libgit.git_repository_open(
  Pointer.fromAddress(repo.address),
  thisRepoLocation,
); // error = 0
```

I think this might be a problem with how I constructed my pointer. Is there a recommended way to construct a pointer of a pointer?

Project link for reference: https://gitlab.com/GZGavinZhao/libgit2.dart. You can clone it (recursively) and run `grind build-cmake` to build the libraries to the `build` directory. It's very light and only takes less than 50MB of space and <2 minutes. After that, run `dart run example/example.dart` in the project root location.

Thank you for your help!

**Comment by dcharkes** [comment]
For an out parameter you need to have allocated some memory (pointed to by a `Pointer<Pointer<git_repository>>` where libgit can write the `Pointer<git_repository>` result value to.

Try

```dart
import 'package:ffi/ffi.dart';

final Pointer<Pointer<git_repository>> repoOut = calloc<Pointer<git_repository>>();
int error = libgit.git_repository_init(
  repoOut,
  location,
  0,
);
```

For reference, see examples of out parameters in the SQLite bindings: https://github.com/dart-lang/sdk/blob/main/samples/ffi/sqlite/lib/src/database.dart

**Comment by GZGavinZhao** [comment]
Is there a difference between `malloc` and `calloc` in terms of performance?

**Comment by dcharkes** [comment]
`calloc` initializes the memory to zero, `malloc` does not.

In other word:

```dart
final Pointer<Pointer<git_repository>> repoOut = calloc<Pointer<git_repository>>();
final Pointer<git_repository> repo = repoOut.value;
assert(repo == nullptr);
assert(repo.address == 0);
```

Which is exactly what the C code in the official docs does:

```c
git_repository *repo = NULL; // same as the dart repo which is a null pointer
&repo; // same as repoOut which is a pointer to a null pointer.
```

**Comment by GZGavinZhao** [comment]
Now I understand. Thank you for your help! <3
