### ISSUE TITLE
Passing Image Data to native c++ function and reconstructing image

### ISSUE THREAD

**Issue by muck27** [dart-lang/ffi#126]
1. I am retrieving a Camera Image from the camera Controller and concatenating the planes data of the image with this piece of code:

```dart
Pointer<Uint8> concatenatePlanes(List<Plane> planes) {
    int totalBytes = 0;
    for (int i = 0; i < planes.length; ++i) {
      totalBytes += planes[i].bytes.length;
    }
    final pointer = malloc.allocate<Uint8>(totalBytes);
    final bytes = pointer.asTypedList(totalBytes);
    int byteOffset = 0;
    for (int i = 0; i < planes.length; ++i) {
      final length = planes[i].bytes.length;
      bytes.setRange(byteOffset, byteOffset += length, planes[i].bytes);
    }
    return pointer;
}
```

2. I pass this pointer to the signature of my c++ function :+1: 
```dart
    int height = args.height;
    int width = args.width;
    int channels = args.img_.planes.length;
    Pointer<Uint8> p = concatenatePlanes(args.img_.planes);

    Pointer<Uint32> s = malloc.allocate(1);
    s[0] = args.img_.planes[0].bytes.length;


    print("got hereee $height $width $channels ");
    final dylib = Platform.isAndroid
        ? DynamicLibrary.open("libOpenCV_ffi.so")
        : DynamicLibrary.process();


    final bgsLive = dylib.lookupFunction<Void Function(Pointer<Uint8>, Pointer<Uint32> ,Int32, Int32,Int32), void Function(Pointer<Uint8>, Pointer<Uint32> , int,int,int)>('liveBgs');
    bgsLive(p,s,args.width,args.height,args.count);

    malloc.free(s);
    malloc.free(p);
```

3. My c++ function does this task:
```c++
void liveBgs (uchar *buf, uint *size, int width, int height, int count){

    cv::Mat image=cv::Mat(cv::Size(width,height), CV_8UC4, buf, cv::Mat::AUTO_STEP);
    cv::imwrite("/data/user/0/com.hg.homeground/cache/"+ to_string(count) + "_.jpg",image);

}
```

Issues:
1. The image gets incorrectly created
2. The app crashes with this error: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x735f7d7002

How can I successfully pass image data to the c++ function and why is my app crashing after writing to the image unsuccessfully though even when I have removed the pointers after consumption?

**Comment by dcharkes** [comment]
What do you mean with incorrectly created?

A segfault could be anything.

Do you have a repo with a reproduction available?

Side note: We have multiple projects doing OpenCV with `dart:ffi` already. You could consider reusing (and contributing to) these instead of starting a new project.

**Comment by muck27** [comment]
Hey @dcharkes thanks for the instant reply.
Could you possibly redirect me to some implementations of dart ffi connected with opencv? I am particulary looking for dart ffi functions that work with image buffers..
![0_](https://user-images.githubusercontent.com/48056260/144849427-b4277ec3-4510-4eaf-9818-c18c1fe253eb.jpg)

This is the image I was talking about

**Comment by dcharkes** [comment]
Context: Are you doing Flutter or Dart standalone? And what platform?

A quick search on the internet:

* https://github.com/as1605/opencv_flutter_ffi
* https://github.com/westracer/flutter_native_opencv

It's hard to see what's wrong with your image. Guessing by the pattern repeating 4 times I would assume 8 bits are read as 32 bits or the other way around. One would have to actually debug what is going on in the native and Dart code.

Same with a segfault. One will likely have to run the application with the native debugger to see where in C/C++ the segfault occurs.

**Comment by muck27** [comment]
I am doing dart + native using ffi .... Hey I am also earnestly looking for native debuggers. My use case is to debug the c++ part of the code in android studio. Does an extension for this use case exist ? If yes, how can I get my hands on one?

Regards

**Comment by dcharkes** [comment]
Here is some documentation on how to run the native debugger: https://github.com/dart-lang/ffi/issues/47#issuecomment-644827551

**Comment by muck27** [comment]
Hey dcharkes thanks a ton for your help...I was finally able to reconstruct my image by passing in image plane data from all 3 channels.
Will close the issue !!

**Comment by mostafaramadann** [comment]
How did you do it, what was wrong in your code, I hope you can help @muck27
