### ISSUE TITLE
Can I use C call dart function?

### ISSUE THREAD

**Issue by obweix** [dart-lang/ffi#129]
Can I use C call dart function? Thanks.

**Comment by dcharkes** [comment]
Only if you start by running the Dart VM.

If you use the Dart VM execution thread to call into C, you can on that thread call back into Dart. You can create function pointers to Dart functions with `fromFunction`.

We do not currently support calling into Dart on different threads. For that you will need to use message passing through native ports. See the link to the sample code in the first comment in https://github.com/dart-lang/sdk/issues/37022.

**Comment by obweix** [comment]
Thank you so much~
