### ISSUE TITLE
String to NativeUtf8

### ISSUE THREAD

**Issue by nhathoang0110** [dart-lang/ffi#145]
Why I can not using toNativeUtf8
![image](https://user-images.githubusercontent.com/55668910/172719110-e9102d51-9a9e-433a-ab89-712b4594d5d7.png)
![image](https://user-images.githubusercontent.com/55668910/172719153-a2c9d1d4-be55-4702-84f2-2bb05b4a9e74.png)

**Comment by dcharkes** [comment]
`import 'package:ffi/ffi.dart'`.

It's an extension method in this package.

**Comment by dcharkes** [comment]
I'm assuming your issue is solved, closing the issue. Please reopen if the issue persists.
