### ISSUE TITLE
Make free an extension member on Pointer?

### ISSUE THREAD

**Issue by simolus3** [dart-lang/ffi#16]
Now that `Pointer.free` was removed from the sdk, I'm wondering if this library could make `free` an extension method on `Pointer`. This would make it easier to migrate and provide an api that's easier to discover for new users. 

The effort for this should be fairly minimal, I could open a PR for this if it's desirable to have this api in the library.

**Comment by mkustermann** [comment]
For symmetry reasons one might argue that `allocate` and `free` should be both top-level functions (similar to C code which uses `malloc`/`free`). A user has also the choice to use different allocation/freeing strategies - adding a `Pointer.free` extension method would select one particular mechanism for freeing.

There was also another subtle change: Before `Pointer.free()` would actually zero out the address as a side-effect of calling `Pointer.free()`. For various reasons this is disallowed now - the address in a `Pointer` is final. Making `free` an extension method might would not allow this zeroing of the address.

/cc @dcharkes @sjindel-google Any opinions?

**Comment by dcharkes** [comment]
I don't have a very strong opinion, but I'd rather not have both an extension method and a top level function in `package:ffi`. It's very simple for people to write their own helper extension method, but they cannot call it free, because name resolution will resolve to the instance method.

**Comment by simolus3** [comment]
> It's very simple for people to write their own helper extension method

Yeah, that's what I was doing as well. I just thought others could be doing the same thing, which might justify it just being done in this library.

> they cannot call it free, because name resolution will resolve to the instance method

I thought you removed `Pointer.free` from the SDK, did I miss something?

> A user has also the choice to use different allocation/freeing strategies - adding a `Pointer.free` extension method would select one particular mechanism for freeing.

I would assume that a user importing this library, which provides the top-level `allocate` and `free` methods, would actually want to use those. Otherwise, a user could just `import 'package:ffi/ffi.dart' hide allocate, FreePointerExtension`. So as far as I can see, this would be the same for top-level functions or extensions.

> For symmetry reasons one might argue that `allocate` and `free` should be both top-level functions (similar to C code which uses `malloc`/`free`)

Writing `myPointer.free()` subjectively feels more Darty to me, but we can't define extension factories so the lack of symmetry is off-putting for sure.

**Comment by dcharkes** [comment]
> > It's very simple for people to write their own helper extension method
> 
> Yeah, that's what I was doing as well. I just thought others could be doing the same thing, which might justify it just being done in this library.
> 
> > they cannot call it free, because name resolution will resolve to the instance method
> 
> I thought you removed `Pointer.free` from the SDK, did I miss something?

Ah right, my bad. :)

> > A user has also the choice to use different allocation/freeing strategies - adding a `Pointer.free` extension method would select one particular mechanism for freeing.
> 
> I would assume that a user importing this library, which provides the top-level `allocate` and `free` methods, would actually want to use those. Otherwise, a user could just `import 'package:ffi/ffi.dart' hide allocate, FreePointerExtension`. So as far as I can see, this would be the same for top-level functions or extensions.
> 
> > For symmetry reasons one might argue that `allocate` and `free` should be both top-level functions (similar to C code which uses `malloc`/`free`)
> 
> Writing `myPointer.free()` subjectively feels more Darty to me, but we can't define extension factories so the lack of symmetry is off-putting for sure.

You can put static methods on extensions, but you can only call them on the extension:

```dart
extension AllocateOnPointer on Pointer {
  static Pointer<T> allocate<T extends NativeType>() => allocate<T>();
}

main(){
  final p = AllocateOnPointer.allocate<Int8>();
}
```

**Comment by simolus3** [comment]
Thanks for all the suggestions @dcharkes, I've just migrated my code to the 2.6.0-dev.8 version and the new `val`/`ref` apis are way more fun to use than the old `load`!

Most of my `Struct`s are empty interfaces now so that I can define an `extension on Pointer<Utf8> { String readString() {...} }`, which simplifies usages a lot. Making those (breaking) changes on this package is probably not worth it though, so I'm closing this issue.

**Comment by dcharkes** [comment]
> Thanks for all the suggestions @dcharkes, I've just migrated my code to the 2.6.0-dev.8 version and the new `val`/`ref` apis are way more fun to use than the old `load`!

Thanks, that was what we were aiming for!
