### ISSUE TITLE
missing SSL_CTX_set1_curves_list

### ISSUE THREAD

**Issue by vincent-iQontrol** [dart-lang/ffi#169]
I have a certificate with ECDSA cipher with secp256r1 curve. There is no way to set it. Only SSL_CTX_set_cipher_list is available.

**Comment by dcharkes** [comment]
@vincent-iQontrol `package:ffi` does not expose any SSL symbols at all, what are you referring to?

**Comment by vincent-iQontrol** [comment]
Sorry wrong place, keep it going guys. This can be closed.
