### ISSUE TITLE
[ffi] Helpers for interacting with C data

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/ffi#17]
There are a number of helpful facilities which can be built on top of the FFI foundation and should probably be included in `dart:ffi`, for example:

* `CString`: wrapper for strings allocated in C
* `CArray<T>`: wrapper for arrays allocated in C, compatible with List, Iterable, TypedData, etc. types

Suggestions for others are welcome!

**Comment by devxpy** [comment]
Hey, I was just wondering how `StructPointer` can be initialized.

With the earlier API, I just used:

```dart
var ptr = ffi.Pointer<Struct>.allocate();
ptr.store(struct);
```

But I can't find a way to do this with the new `extensions` interface.

Considering how commonplace `struct *` is, it'd be a pity if this wasn't supported.

**Comment by dcharkes** [comment]
@devxpy We currently do not support storing a whole struct by value. `struct` in `ptr.store(struct)` seems to indicate that would have a `struct` by value.

Assuming that is a Pointer to a struct, in order to allocate a pointer you use allocate from _this package_, just pin it to the latest dev version. (We'll release a new version when Dart 2.6 is released.)

In this package the signature would be

```dart
Pointer<Struct> struct; // from somewhere
final ptr = allocate<Pointer<Struct>>();
ptr.value = struct;
```

**Comment by devxpy** [comment]
Sorry for not filling in these details earlier.

`struct` is a struct by value, not a pointer to a struct.

---

To elaborate, this is what I wanted - 

```dart
class FPDF_LIBRARY_CONFIG extends Struct {
    ...
}

FPDF_LIBRARY_CONFIG config = FPDF_LIBRARY_CONFIG();
Pointer<FPDF_LIBRARY_CONFIG> ptr = allocate<FPDF_LIBRARY_CONFIG>();
ptr.value = config;
```
But that results in the following error -

```
error: The setter 'value' isn't defined for the class 'Pointer<FPDF_LIBRARY_CONFIG>'. (undefined_setter at [pdfium] lib/src/functions.dart:34)
```

---

I want this because the underlying library expects `FPDF_LIBRARY_CONFIG*` to be passed as an argument to `FPDF_InitLibraryWithConfig()`;

```c
// fpdfview.h
FPDF_EXPORT void FPDF_CALLCONV FPDF_InitLibraryWithConfig(const FPDF_LIBRARY_CONFIG* config);
```

**Comment by dcharkes** [comment]
We do not support having C-values in the Dart heap (yet). So you want to allocate the C-memory first, and then write to the individual fields. However, nothing is stopping you from writing a constructor that does exactly that.

```dart
class Coordinate extends Struct {
  @Double()
  double x;

  @Double()
  double y;

  Pointer<Coordinate> next;

  factory Coordinate.allocate(double x, double y, Pointer<Coordinate> next) {
    return allocate<Coordinate>().ref
      ..x = x
      ..y = y
      ..next = next;
  }
}
```

See our [samples](https://github.com/dart-lang/sdk/blob/master/samples/ffi/sample_ffi_structs.dart).

For your example

```dart
Pointer<FPDF_LIBRARY_CONFIG> ptr = allocate<FPDF_LIBRARY_CONFIG>();
// ptr.field1 = value1;
// ptr.field2 = value2;
// ...
// (all of the above could be put in a FPDF_LIBRARY_CONFIG.allocate constructor.)
// call FPDF_InitLibraryWithConfig with ptr.
```

For allocating lists you could write your own helpers:

```dart
Pointer<Int32> allocateList(List<int> values) {
  final ptr = allocate<Int32>(count: values.length);
  for (int i = 0; i < values.length; i++) {
    ptr[i] = values[i];
  }
  return ptr;
}
```

**Comment by phanirithvij** [comment]
@dcharkes | @sjindel-google

How to get data from the Pointer? There was a method `Pointer.load` in `ffi: ^0.1.1` https://github.com/dart-lang/samples/commit/3933ad3a77ecb4e70a438e4493b8f63a241ded58#diff-c0171e4ec91da7fa02e58b3c5c6ee825L57 but now in the `ffi: ^0.1.3-dev.3` it's removed.

I'm trying to get a `String` from a `Utf16` pointer as there's no helper function available in the `Utf16` like `Utf16.fromUtf16` similar to `Utf8.fromUtf8` which's provided in `ffi`.

In `ffi:^0.1.1` based on the example provided at https://github.com/dart-lang/samples/commit/3933ad3a77ecb4e70a438e4493b8f63a241ded58#diff-3daffcc813b038ea22d2feea46e846b0L14 I was using this
```dart
  String fromUtf16(Pointer ptr) {
    final units = List<int>();
    var len = 0;
    while (true) {
      final char = ptr.elementAt(len++).load<Utf16>().char;
      if (char == 0) break;
      units.add(char);
    }
    return String.fromCharCodes(units);
  }
```
Now as `load` isn't available, I'm doing this in the loop, as I need a 1 byte char.
```dart
//   while()...
      final int char = (ptr.elementAt(len++) as Pointer).cast<Int8>().value;
      print(ptr.elementAt(len).address); // prints the same value everytime 
      print("$char, $len"); // len does increase
// same as above
```
But this is giving me the same value in every iteration, as it's going to the same address every time.
Am I missing something?

My repo source is [here](https://github.com/phanirithvij/cross-wallpaper/commit/4392861460a0078874c21c3414af7e43584af0b0#diff-1a01d3bcadb3249b5ed56bcd0672d11cR38) (If needed).

**Comment by dcharkes** [comment]
The sample code got moved into this package https://github.com/dart-lang/ffi/blob/master/lib/src/utf8.dart

I see that the Utf16 variant is missing some methods, but they should be similar to the Utf8 ones.

P.S. feel free to post your questions on the mailing list dart-ffi@googlegroups.com or open separate GitHub issues.

**Comment by phanirithvij** [comment]
I'll open a separate issue. I'll need a more detailed answer.
I'll delete my comments here once that issue is resolved.

**Comment by Sunbreak** [comment]
Any progress recently?

**Comment by dcharkes** [comment]
> Any progress recently?

* Utf8 is in `package:ffi`
* `Pointer`s have the `asTypedList` extension method for easy iteration in Dart.

Further String work is tracked in https://github.com/dart-lang/sdk/issues/39787. We do not have any plans for any iteration support beyond `asTypedList`.

Closing this issue. Feel free to request more features or send pull requests.
