### ISSUE TITLE
How to C native call the dart function of the uint8list datatype？

### ISSUE THREAD

**Issue by hyue7** [dart-lang/ffi#173]
Dear all!
What I need to implement is to call the dart function from C.
The dart code like this:
```
typedef NativeAsyncCallbackFunc = Pointer<Uint8> Function();
Future<Uint8List> function(Uint8List param) async {
...
}
```
The C callback like this:
`unsigned char* (*callback)()`
some error occurred:
`The type 'Future<Uint8List> Function()' must be a subtype of 'Pointer<Uint8> Function()' for 'fromFunction'.`

The uint8list datatype has no C native datatype corresponding to it. So how can I call the dart function which return type is Uint8List through FFI?

**Comment by hyue7** [comment]
> Right now a `Uint8List` cannot be given to C code, one has to copy into a e.g. `malloc()`ed buffer and pass that `Pointer<Uint8>` and `length`

Thanks for your response!  Do you have any example code about pass `Pointer<Uint8>` and `length` to C?

**Comment by mkustermann** [comment]
> Thanks for your response! Do you have any example code about pass Pointer<Uint8> and length to C?

Something like this will do it:
```dart
import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

main() {
  final bytes = Uint8List(10);
  callC(bytes);
}

final foobar = DynamicLibrary.process().lookupFunction<
    Void Function(Pointer<Uint8>, IntPtr),
    void Function(Pointer<Uint8>, int)>('foobar');

void callC(Uint8List bytes) {
  // Copy data out into C buffer:
  final Pointer<Uint8> pointer = malloc.allocate(bytes.length);
  pointer.asTypedList(bytes.length).setRange(0, bytes.length, bytes);
  // Call C function with C buffer.
  foobar(pointer, bytes.length);
  // Free the C buffer.
  malloc.free(pointer);
}
```

**Comment by hyue7** [comment]
Thanks for your help!! I can use it to pass Pointer<Uint8> and length down to C code.
But I also have parameters to pass from C(unsigned char*,length) to Dart(Uint8List), how to change the data type？
Dart don't have any datatype correspond to it Pointer<Uint8>.
For example:
dart code:
```
typedef NativeAsyncCallbackFunc = Void Function(Pointer<Uint8>, Int64);
typedef NativeAsyncFunc = Void Function(
  Pointer<NativeFunction<NativeAsyncCallbackFunc>> callback,
);
typedef dartAsyncFunc = void Function(
  Pointer<NativeFunction<NativeAsyncCallbackFunc>> callback,
);
void func(<something>, int challengeLen) {
....
  }
```
C code the callback is:
`typedef void (*FuncLicenseCB)(uint8_t *challenge, uint64_t challenge_len);`
How should I fill in <something> if I want to pass `func` as a callback to C?

**Comment by mkustermann** [comment]
> C code the callback is: `typedef void (*FuncLicenseCB)(uint8_t *challenge, uint64_t challenge_len);`

Would something like this work for you:
```dart
void func(Pointer<Uint8> challenge, int challengeLen) {
  final Uint8List bytes = challenge.asTypedList(challengeLen);
  // ... remember to manually memory manager `challenge` ....
}
....
main() {
  final callback = Pointer.fromFunction<Void Function(Pointer<Uint8>, Uint64)>(func);
  // ... pass `callback` to C code. 
}
```
?

**Comment by hyue7** [comment]
Thank you so much!! I have sloved the problem~Have a good day :)
