### ISSUE TITLE
Pass a Dart_PersistentHandle list / buffer from C to Dart?

### ISSUE THREAD

**Issue by natinusala** [dart-lang/ffi#182]
I want to pass a list of `Dart_PersistentHandle` from C back to Dart (inside a callback).

So I made this struct:

```c
typedef struct _persistent_handle_list
{
    Dart_PersistentHandle* items;
    size_t length;
} persistent_handle_list;
```

In C, I `malloc` the items inside, set `length` and return the struct by value.

In Dart, ffigen gives me a nice `persistent_handle_list` struct:

```dart
class _persistent_handle_list extends ffi.Struct {
  external ffi.Pointer<ffi.Handle> items;

  @ffi.Size()
  external int length;
}

typedef persistent_handle_list = _persistent_handle_list;
```

Now here is my question: how can I convert this pointer to a usable Dart `List<Object>`? There doesn't seem to be any `HandleList` / `asTypedList` that I can use.

 I can call `elementAt` but it just gives me a `Pointer<Handle>` which I cannot do anything with. Am I approaching this wrong? Is there a better / easier way, or does FFI not allow this at the moment?

**Comment by dcharkes** [comment]
With your approach the next step would be to do an FFI call to unwrap the handle: Dart signature `Object Function(Pointer<Handle>)`, C signature in Dart `Handle Function(Pointer<Handle>)`.

(An alternative approach would be to add the elements to a Dart list through dart_api.h and return a single handle to that Dart list. However, that is likely slower than doing FFI calls to unwrap the handle, and it adds a dependency on symbols that are not in dart_api_dl.h which prohibits using it in Flutter.)

How many handles are we talking about in this list? If it is many and slow, we should add a primitive to `dart:ffi` that can speed such use case up.

**Comment by natinusala** [comment]
Thank you for your answer!

My list currently holds very few items (actually never more than 10). But I might use that struct in more places in my project where I might need lists in the future, so I cannot really tell how large it will become. This is also why I don't want to use a static array with a fixed size of 10.

By the way, to use `elementAt` I need to cast the pointer to `Void` first and then back to `Handle`, otherwise it tells me `Error: Expected type 'Handle' to be a valid and instantiated subtype of 'NativeType'`:

```dart
  // "Working"
  final handles = [
    for (var i = 0; i < list.length; i++)
      list.items.cast<Void>().elementAt(i).cast<Handle>()
  ];

  // Error: Expected type 'Handle' to be a valid and instantiated subtype of 'NativeType'.
  final handles = [
    for (var i = 0; i < list.length; i++) list.items.elementAt(i)
  ];
```

I don't know if that's normal? Or if the cast even works, but it seems to me that `Handle` inherits from `NativeType` like all the other types.

**Comment by mkustermann** [comment]
Please notice that there's a difference between persistent handles (`Dart_PersistentHandle` in C++, no Dart equivalent) and local handles (`Dart_Handle` in C++, `Handle` from `dart:ffi` native signatures).

>  Dart signature Object Function(Pointer<Handle>), C signature in Dart Handle Function(Pointer<Handle>).

Actually what one would need to do today is to call this method from our [include/dart_api.h](https://github.com/dart-lang/sdk/blob/main/runtime/include/dart_api.h#L419):
```c++
/**
 * Allocates a handle in the current scope from a persistent handle.
 */
DART_EXPORT Dart_Handle Dart_HandleFromPersistent(Dart_PersistentHandle object);
```
This will give a local handle back. If one binds to that C function using
```
@Native<Handle Function(Pointer<Void)>("Dart_HandleFromPersistent")
Object handleFromPersistentHandle(Pointer<Void> persistentHandle);

// or similar .asFunction<>() call.
```
then one gets the object back.

(The `dart:ffi` `Handle` class refers local handles)

**Comment by natinusala** [comment]
Are they not interchangeable? Since ffigen translated `Dart_PersistentHandle` to `ffi.Handle` I thought they were equivalent once back in the Dart realm. This automatic conversion seem to work fine in other scenarios in my code. Maybe disabling the `Dart_PersistentHandle` to `ffi.Handle` conversion in ffigen can avoid this mistake?

**Comment by mkustermann** [comment]
> Are they not interchangeable? Since ffigen translated `Dart_PersistentHandle` to `ffi.Handle`

Not really. One can e.g. `Dart_DeletePersistentHandle(<persistent-handle>)` - one cannot do so on a local handle.

**Comment by natinusala** [comment]
I was able to make it work by adding a small C function `Dart_Handle persistent_handle_list_get(persistent_handle_list list, size_t idx)`, it does the `Handler` to `Object` conversion for me and it's simpler overall. 

I guess my initial approach was needlessly complicated after all.

I'll have to figure out the difference between a persistent handle and a local handle once it's converted to an `Object`, I was confused because I've been using persistent handles everywhere for the time being (for simplicity, I wanted to prototype my thing first and take care of memory later), and it seemed to work fine? I thought it only impacted the lifetime of the object "escaped" out of Dart? 

As long as the handle is "valid" (the definition of "valid" being the difference between a local and persistent one), Dart should accept it shouldn't it?

**Comment by mkustermann** [comment]
> > Are they not interchangeable? Since ffigen translated Dart_PersistentHandle to ffi.Handle
>
> Not really. One can e.g. Dart_DeletePersistentHandle(<persistent-handle>) - one cannot do so on a local handle.

To clarify: They are compatible for reading purposes since they store the heap object pointer in the same offset, but not generally interchangeable. It seems that we actually promise this fact in the API description, so it's actually safe thing to do. See [include/dart_api.h](https://github.com/dart-lang/sdk/blob/39136c15010029/runtime/include/dart_api.h#L238)
```c
/*
 * ...
 * The type Dart_Handle represents a handle (both local and persistent).
 * The type Dart_PersistentHandle is a Dart_Handle and it is used to
 * document that a persistent handle is expected as a parameter to a call
 * or the return value from a call is a persistent handle.
 */
```
