### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffi#196]
@mit-mit @devoncarew

I don't have access to https://github.com/dart-lang/ffi/settings.

**Comment by mit-mit** [comment]
Shall I go ahead and do this now?

**Comment by dcharkes** [comment]
Yes please

**Comment by mit-mit** [comment]
Done!

**Comment by devoncarew** [comment]
For people who run across this issue, to update a local clone, run:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
