### ISSUE TITLE
How to access the Pointer value

### ISSUE THREAD

**Issue by phanirithvij** [dart-lang/ffi#21]
How to get data from the Pointer? There was a method `Pointer.load` in `ffi: ^0.1.1` https://github.com/dart-lang/samples/commit/3933ad3a77ecb4e70a438e4493b8f63a241ded58#diff-c0171e4ec91da7fa02e58b3c5c6ee825L57 but now in the `ffi: ^0.1.3-dev.3` it's removed.

I'm trying to get a `String` from a `Utf16` pointer as there's no helper function available in the `Utf16` like `Utf16.fromUtf16` similar to `Utf8.fromUtf8` which's provided in `ffi`.

In `ffi:^0.1.1` based on the example provided at https://github.com/dart-lang/samples/commit/3933ad3a77ecb4e70a438e4493b8f63a241ded58#diff-3daffcc813b038ea22d2feea46e846b0L14 I was using this
```dart
  String fromUtf16(Pointer ptr) {
    final units = List<int>();
    var len = 0;
    while (true) {
      final char = ptr.elementAt(len++).load<Utf16>().char;
      if (char == 0) break;
      units.add(char);
    }
    return String.fromCharCodes(units);
  }
```
Now as `load` isn't available, I'm doing this in the loop, as I need a 1 byte char.
```dart
//   while()...
      final int char = (ptr.elementAt(len++) as Pointer).cast<Int8>().value;
      print(ptr.elementAt(len).address); // prints the same value everytime 
      print("$char, $len"); // len does increase
// same as above
```
But this is giving me the same value in every iteration, as it's going to the same address every time.
Am I missing something?

My repo source is [here](https://github.com/phanirithvij/cross-wallpaper/commit/4392861460a0078874c21c3414af7e43584af0b0#diff-1a01d3bcadb3249b5ed56bcd0672d11cR38) (If needed).

**Comment by dcharkes** [comment]
I think the specific issue here is that `Utf16` has no fields, so it's size is 0. You can check this with `sizeOf<Utf16>()`. The workaround is to do `ptr.cast<Int8>().elemAt(len)` instead.

N.b. This shows that we should clean up these Utf8 and Utf16 strings.

**Comment by phanirithvij** [comment]
I get only the first character if I use that `ptr.cast<Int8>().elemAt(len)` and the second character becomes `0`

**Comment by phanirithvij** [comment]
I've figured it out.
I need to skip a byte every time in the loop.
```dart
    while (true) {
      final int char = ptr.cast<Int8>().elementAt(len++).value;
      // skip one byte
      final int _ = ptr.cast<Int8>().elementAt(len++).value;
      print(ptr.cast<Int8>().elementAt(len-1).address);
      print("$char, $len");
      if (char == 0) break;
      units.add(char);
    }
```
But this doesn't seem to be a good thing to do 😕

**Comment by phanirithvij** [comment]
Oh `final int char = ptr.cast<Int16>().elementAt(len++).value;` can be done

**Comment by phanirithvij** [comment]
closing this

**Comment by phanirithvij** [comment]
How is this working exactly? Don't we first need to get the element and cast it to an int?  @dcharkes

**Comment by dcharkes** [comment]
```dart
Pointer<Int16> ptr; // interprets the C memory as 16-bit integers.
Pointer<Utf16> ptr2; // does not know how to interpret the C memory, as Utf16 is an opaque struct.
```

The marshalling from C integers to Dart integers is done on the `.value` and `.value = `.
