### ISSUE TITLE
flutter 1.10.15 compatibility 

### ISSUE THREAD

**Issue by hanabi1224** [dart-lang/ffi#23]
Flutter 1.10.15 has rolled out breaking changes that are only compatible with ffi: 0.1.3, however, the dart sdk version of Flutter 1.10.15 is dart 2.6-dev which cannot reference ffi:0.1.3 (required dart 2.6 as lower bound) . I think a ffi:0.1.3+1 with a relaxed dart sdk lower bound would fix the issue, also it will be great to release +n patch to 0.1.2 downward to set a dart sdk upper bound to avoid bad reference

**Comment by dcharkes** [comment]
We're at Flutter 1.12, so this is resolved for the latest stable.

Please reopen if you're still blocked.
