### ISSUE TITLE
Bad UTF-8 encoding 0x50 , after using use malformed some extra gibberish text is added

### ISSUE THREAD

**Issue by anuragvohraec** [dart-lang/ffi#24]
Hi Team,

I am testing ffi use in flutter. my C function returns a Hello user message to flutter.
However the message I recieve at flutter end fails when I convert the pointer back to string using:  Utf8.fromUtf8(Pointer<Utf8> pointerReturnedByC).

I am getting **Bad UTF-8 encoding 0x50 at offset 6**, whle using Utf8.fromUtf8 function.
To debuge the issue I copied the code of Utf8 and created a class ExtUtf8. In it I modified its fromUtf8 method as such:

```static String fromUtf8(Pointer<Utf8> string) {
   try{
     final int length = strlen(string);
     print("############## Length: $length");
     //ByteBuffer bb = string.cast<Uint8>().asTypedList(length).buffer;
     return utf8.decode(Uint8List.view(string.cast<Uint8>().asTypedList(length).buffer, 0, length), allowMalformed: true);
   }catch(e,s){
     print(e);
     print(s);
   }
  }
```

I enabled the allowMalformed flag to see if my string is even returning from C.
Its beeing returned by my C code , but ffi some how adds the extra gibberish memory locations to it.
My C function is :

```
char* sayhellotouser(char username[]){
    char postfix[]=" Good Morning!";
    char *prefix = sayhello(username);
    char *result = joinStr(prefix,postfix);
    return result;
}
char *sayhello(char* username){
    char *prefix = "Hello ";
    return joinStr(prefix, username);
}

char *joinStr(char firstString[],char secondString[]){
    int size = strlen(firstString)+ strlen(secondString)+1;
    char *result= malloc(size);
    return strcat(strcat(result,firstString),secondString);
}
```
My code is at : https://github.com/anuragvohraec/testdartffi.git

Is it something I am doing wrong or their is a bug in the code ?

**Comment by mkustermann** [comment]
Briefly looking over it, this code sticks out:
```
    char *result= malloc(size);
    return strcat(strcat(result,firstString),secondString);
```
Notice that the inner `strcat(result, firstString)` uses `result` just from `char* result = malloc(size)`. There is no guarantee that the memory returned from `malloc` is 0-initialized, though `strcat(result, ...)` assumes that `result` is a valid 0-terminated c-string.

So at least you need to change this to
```
    char *result= malloc(size);
    result[0] = '\0';
    return strcat(strcat(result,firstString),secondString);
```

**Comment by anuragvohraec** [comment]
> Briefly looking over it, this code sticks out:
> 
> ```c
> char *result= malloc(size);
> return strcat(strcat(result,firstString),secondString);
> ```
> 
> Notice that the inner `strcat(result, firstString)` uses `result` just from `char* result = malloc(size)`. There is no guarantee that the memory returned from `malloc` is 0-initialized, though `strcat(result, ...)` assumes that `result` is a valid 0-terminated c-string.
> 
> So at least you need to change this to
> 
> ```c
> char *result= malloc(size);
> result[0] = '\0';
> return strcat(strcat(result,firstString),secondString);
> ```

Yep thats the problem. Thank you !

**Comment by anuragvohraec** [comment]
Thi issue can be closed
