### ISSUE TITLE
Error loading prebuilt dynamic library in Flutter plugin

### ISSUE THREAD

**Issue by theochampion** [dart-lang/ffi#25]
Hi there,

I'm trying to use my C++ library in a Flutter project but after a build without error, the library is not found:

```
ArgumentError (Invalid argument(s): Failed to load dynamic library (dlopen failed: library "librPPG.so" not found))
```

Here is my code:

`librPPG.so` in `android/src/main/jniLibs/`

in `android/build.gradle`
```
android {
    compileSdkVersion 28

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.jniLibs.srcDirs += 'src/main/jniLibs'
    }

    defaultConfig {
        externalNativeBuild {
            cmake {
            }
        }
        minSdkVersion 21
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}
```

in `android/CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.4.1)

add_library(librPPG SHARED IMPORTED )
set_target_properties(librPPG PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/librPPG.so)
```

and the library is loaded in my plugin like so:

```dart
final DynamicLibrary rPPGLib = Platform.isAndroid
    ? DynamicLibrary.open("librPPG.so")
    : DynamicLibrary.open("rPPG.framework/rPPG");
```

What am I missing here?

**Comment by theochampion** [comment]
turned out the ABI subdirectory is required for dlopen to find the lib. Modifying my `CMakeLists.txt` like so solved the issue

```
cmake_minimum_required(VERSION 3.4.1)

add_library(librPPG SHARED IMPORTED GLOBAL)
set_target_properties(librPPG PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/librPPG.so)
```

**Comment by gfiury** [comment]
For everyone who gets here, it is important to have the specifics files for ANDROID_ABI [value](https://developer.android.com/ndk/guides/abis)

I have for example `src/main/jniLibs/armeabi-v7a/librPPG.so` file but the project needed the others ABI values to avoid the 

`ArgumentError (Invalid argument(s): Failed to load dynamic library (dlopen failed: library "librPPG.so" not found))`
