### ISSUE TITLE
Pass Uint8List to Pointer<Void>

### ISSUE THREAD

**Issue by theochampion** [dart-lang/ffi#27]
Hi there,

I have a C function with the Following signature
```C
bool sendFrame(int width, int height, int channelNumber, void *data, bool clone);
```
data here being a raw image.

My ffi function signature is:

```dart
  final int Function(int, int, int, Pointer<Void>, int) rPPGSendFrame = rPPGLib
      .lookup<
          NativeFunction<
              Int32 Function(
                  Int32, Int32, Int32, Pointer<Void>, Int32)>>("sendFrame")
      .asFunction();
```
(the bools have to be converted to ints because the bool type is not supported yet (right?))

I'm trying to call this method from dart with a `Uint8List` coming from a frame of the camera stream https://pub.dev/documentation/camera/latest/camera/Plane-class.html but I'm not sure how to convert/allocate my `Uint8List` to `void *`

Any idea?

Cheers!

**Comment by dcharkes** [comment]
Hey @theochampion,

The Uint8List lives in the Dart heap, which is garbage collected, and the objects might be moved around by the garbage collector. So, you'll have to convert it into a pointer into the C heap.

```dart
  Uint8List list;
  final pointer = allocate<Uint8>(count: list.length());
  for(int i = 0, ...){
    pointer[i] = list[i];
  }
  final voidStar = pointer.cast<Void>();
  // function call
  free(pointer);
```

**Comment by dcharkes** [comment]
@theochampion, does this work for you?

I'll close this issue, please reopen if need be.

**Comment by muck27** [comment]
@dcharkes I am trying to get image data copied as a pointer and pass it to a opencv c++ function using dart ffi. Could you give me a hint of how to make it work?

TIA

**Comment by dcharkes** [comment]
@muck27 could you give more details.

P.S. Feel free to open a new issue rather than reusing an old one if you have a different problem.

**Comment by dcharkes** [comment]
> Also from which package `allocate` is coming from?

This package. `package:ffi`.

> Because `list.length()` is changed to `list.length`

Must have been a typo on my side. It is indeed a property: https://api.dart.dev/stable/2.17.5/dart-core/List/length.html

**Comment by dcharkes** [comment]
Note for people coming across this issue:

1. If you can get the memory in C to begin with (instead of a `Uint8List` in the Dart heap), that would avoid copying all together.
2. Exposing a mem-copy API from Uint8List to Pointers is tracked in https://github.com/dart-lang/sdk/issues/43968.
