### ISSUE TITLE
[dart/vm/ffi] Dynamic library not shipped to phone/simulator on iOS

### ISSUE THREAD

**Issue by rockingdice** [dart-lang/ffi#28]
You can repro by using the latest flutter master branch. 
Try to create a project by:
```flutter create --template=plugin -i objc native_add```

Then follow the link:
https://flutter.dev/docs/development/platform-integration/c-interop

If you run on the iOS simulator, it throws an exception:
```
flutter: The following ArgumentError was thrown building MyApp(dirty, state: _MyAppState#f2f14):
flutter: Invalid argument(s): Failed to load dynamic library (dlopen(native_add.framework/native_add, 1):
flutter: image not found)
flutter:
flutter: The relevant error-causing widget was:
flutter:   MyApp file:///Users/li9s/github/flutter_projects/native_add/example/lib/main.dart:7:23
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
flutter: #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
flutter: #2      nativeAddLib (package:native_add/native_add.dart:8:83)
flutter: #3      nativeAddLib (package:native_add/native_add.dart:7:22)
```
I tried swift project which is working. But there's another issue to use c++ together.

**Comment by rockingdice** [comment]
flutter doctor -v:
```
[✓] Flutter (Channel master, v1.12.1-pre.10, on Mac OS X 10.14.5 18F203, locale zh-Hans-CN)
    • Flutter version 1.12.1-pre.10 at /Users/li9s/github/flutter
    • Framework revision 061d6a04ff (5 hours ago), 2019-12-04 08:07:37 +0800
    • Engine revision 1a96087747
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 e4344a568f)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/li9s/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] Connected device (2 available)
    • LON AL00          • TEV0216C22001731                     • android-arm64 • Android 9 (API 28)
    • iPhone 11 Pro Max • 47A0091B-23C4-4B7D-90E2-E8B5F9FAFAB8 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

```

**Comment by dcharkes** [comment]
> If you run on the iOS simulator, it throws an exception

Does it also throw an exception if run on an iPhone directly? (E.g. does it have the same error on a real phone and on the simulator?)

**Comment by dcharkes** [comment]
I see `DynamicLibrary.open` in the stacktrace. As the documentation mentions, you should use `DynamicLibrary.process` for statically linked libraries on iOS. https://flutter.dev/docs/development/platform-integration/c-interop#ios-and-macos. Please let me know if that solves the issue for you.

**Comment by rockingdice** [comment]
@dcharkes I tried the ```DynamicLibrary.process``` but still not working, it tells me the same error. I'll try if it's working on the device.

**Comment by dcharkes** [comment]
> it tells me the same error

Is it exactly the same? Could you post the stack trace?

> I'll try if it's working on the device.

Great, thanks!

**Comment by dcharkes** [comment]
I'm able to reproduce the issue.

`flutter: Invalid argument(s): Failed to load dynamic library (dlopen(native_add.framework/native_add, 1):`

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown building MyApp(dirty, state: _MyAppState#e9f58):
flutter: Invalid argument(s): Failed to load dynamic library (dlopen(native_add.framework/native_add, 1):
flutter: image not found)
flutter:
flutter: The relevant error-causing widget was:
flutter:   MyApp file:///Users/dacoharkes/ffi-samples/flutter_native_add/native_add/example/lib/main.dart:17:23
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
flutter: #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
flutter: #2      nativeAddLib (package:native_add_example/main.dart:11:22)
flutter: #3      nativeAddLib (package:native_add_example/main.dart:9:22)
flutter: #4      nativeAdd (package:native_add_example/main.dart:13:46)
flutter: #5      nativeAdd (package:native_add_example/main.dart:13:34)
flutter: #6      _MyAppState.build (package:native_add_example/main.dart:62:27)
```

It seems the dynamic library itself is not shipped to the phone/simulator, even though the file is in `ios/Classes/` as described in the documentation. Both `ios/native_add.podspec` and `example/ios/Pods/Local Podspecs/native_add.podspec.json` refer to those classes.

cc @mkustermann

**Comment by dnfield** [comment]
@rockingdice can you include a sample repo that demonstrates this?  Or, could you show us how you've included the library in your application?

**Comment by dcharkes** [comment]
@rockingdice if I follow the steps of the documentation, I run into the same issue.

I was able to get it work by using static linking and looking the symbols up with `DynamicLibrary.process()`.

In order to link the library statically, you have to go into xcode and add the cpp file to the runner.

> Add the C/C++/Objective-C/Swift source files to the Xcode project.

https://flutter.dev/docs/development/platform-integration/c-interop#source-code.

1. Open  the workspace `example/ios/Runner.xcworkspace` in xcode.
2. Right click `Runner`.
3. Select `Add files to "Runner"...`.
4. Select `ios/Classes/native_add.cpp`.

This works both for my device and simulator.

@rockingdice please reopen issue if this doesn't work for you.

**Comment by dcharkes** [comment]
I've created https://github.com/flutter/website/pull/3347 to update the documentation.

**Comment by rockingdice** [comment]
Thank you for your reply!

I still have a question about it - You mentioned that we should add those source files into the Runner project, but I'm writing a plugin, does it have a runner project too? I tried to open it but it opens the example project, I don't think we should put the plugins' code into the app's project.
If not, how could we statically link the codes into the plugin on iOS?
