### ISSUE TITLE
some FormatException when i use Utf8.fromUtf8

### ISSUE THREAD

**Issue by Nightmare-MY** [dart-lang/ffi#32]
this some error from terminal when i use try-catch 
```sh
FormatException: Bad UTF-8 encoding 0x88 (at offset 0)
FormatException: Unfinished UTF-8 octet sequence (at offset 4095)
```
there are always two error
and there is my c code
```c
char *get_output_from_fd(int fd)
{
    int flag = -1;
    flag = fcntl(fd, F_GETFL); //获取当前flag
    flag |= O_NONBLOCK;        //设置新falg
    fcntl(fd, F_SETFL, flag);  //更新flag
    //动态申请空间
    char *str = (char *)malloc((4097) * sizeof(char));
    //read函数返回从fd中读取到字符的长度
    //读取的内容存进str,4096表示此次读取4096个字节，如果只读到10个则length为10
    int length = read(fd, str, 4096);
    if (length == -1)
    {
        free(str);
        return NULL;
    }
    else
    {
        str[length] = '\0';
        return str;
    }
}
```
and i think this char alway end of '\0',so Utf8.fromUft8 can normal convert
so sorry my english,
some helps,thanks

**Comment by dcharkes** [comment]
> FormatException: Bad UTF-8 encoding 0x88 (at offset 0)

This looks suspicious. What is the first character in the file? Are you sure that it is encoded in UTF8?

**Comment by Nightmare-MY** [comment]
![QQ20200225-172146](https://user-images.githubusercontent.com/44189674/75233158-60beae00-57f3-11ea-8c13-d2af1aab0ce6.png)
I found the cause of the problem
This situation is consistent with what I met
if the codeUnits is [229, 142, 187, 229, 142, 187],it can be normal convert,but when it a lot of output from my c code,the first time i just take [int,int,int.......,,229, 142, 187, 229, 142],and the second time i take [187,int,int......],so made this problem

**Comment by Nightmare-MY** [comment]
so i think if i can make sure [*,*] is not a complete codeUnits,i can put it in cache codeUnits,and delete in the original codeUnits,when the second time ,i use cache add output which get in this time ,maybe I can avoid this mistake

**Comment by Nightmare-MY** [comment]
```dart
static String cStringtoString(Pointer<Uint8> str) {
    if (str == null) {
      return null;
    }
    int len = 0;
    while (str.elementAt(++len).value != 0) {}
    List<int> units = List(len);
    for (int i = 0; i < len; ++i) units[i] = str.elementAt(i).value;
    units = Niterm.tmp + units;
    len = len + Niterm.tmp.length;
    Niterm.tmp.clear();
    //只有当为0开头经过二进制转换才小于7位，如果读取到的最后一个字符为0开头，
    //说明这整个UTF8字符占用1个字节，不存在后面还有其他字节没有读取到的情况
    if (units[len - 1].toRadixString(2).length <= 7) {
      return Utf8Codec().decode(units);
    } else {
      int number = 0;
      units.forEach((f) {
        print(f);
      });
      while (true) {
        if (units[len - 1 - number].toRadixString(2).startsWith("10")) {
          //经过一次10开头的便记录一次
          number++;
        } else if (units[len - 1 - number]
            .toRadixString(2)
            .startsWith("1" * (number + 2))) {
          //此时该字节以number+2个字节开始，说明该次读取不完整
          //因为此时该字节开始的1应该为number+1个(10开始的个数加上此时这个字节)
          Niterm.tmp = units.sublist(len - number - 1);
          units.removeRange(len - number - 1, len);
          break;
        } else
          break;
      }
    }
    return Utf8Codec().decode(units);
  }
```
Finally I solved the problem,I wrote a function for my own use,so sorry i am so bad at English,I went to learn how to encode UTF8,And then I found this pattern to find which codeUnits is not complete,anyway thanks

**Comment by dcharkes** [comment]
I'm glad you figured it out. Happy coding!
