### ISSUE TITLE
Utf16 conversion to String is missing

### ISSUE THREAD

**Issue by timsneath** [dart-lang/ffi#35]
As far as I can tell, the FFI interface has no built-in helper method to convert a `Pointer<Utf16>` to a `String`. 

I've created this helper method in my code: 
```dart
String fromUtf16(Pointer pointer, int length) {
  final buf = StringBuffer();
  final ptr = Pointer<Uint16>.fromAddress(pointer.address);

  for (var v = 0; v < length; v++) {
    final charCode = ptr.elementAt(v).value;
    if (charCode != 0) {
      buf.write(String.fromCharCode(charCode));
    } else {
      return buf.toString();
    }
  }
  return buf.toString();
}
```

Seems like this should be part of the `package:ffi` environment, perhaps?

**Comment by dcharkes** [comment]
Feel free to open a PR @timsneath.

**Comment by dcharkes** [comment]
https://github.com/dart-lang/ffi/pull/83
