### ISSUE TITLE
Add dart:ffi like Pointer extensions for more convenient value access

### ISSUE THREAD

**Issue by EPNW** [dart-lang/ffi#36]
For most pointer types dart:ffi specifies an extension to easily access the value, e.g. [`FloatPointer`](https://api.dart.dev/stable/2.7.2/dart-ffi/FloatPointer.html).
We could add an `Utf8Pointer` extension to `Pointer<Utf8>` to access the underlying value without static methods.

**Comment by dcharkes** [comment]
Yes, this package was written before extension methods were released in Dart. Feel free to open a PR.

**Comment by dcharkes** [comment]
https://github.com/dart-lang/ffi/pull/83
