### ISSUE TITLE
Invalid depfile: C:\Users\HP\flutter_code\course_proj\native_add\example\.dart_tool\flutter_build\50ebc546f2b6965eae53e58c91aaea8a\kernel_snapshot.d

### ISSUE THREAD

**Issue by shyamkawale** [dart-lang/ffi#37]
Invalid depfile: C:\Users\HP\flutter_code\course_proj\native_add\example\.dart_tool\flutter_build\50ebc546f2b6965eae53e58c91aaea8a\kernel_snapshot.d
Invalid depfile: C:\Users\HP\flutter_code\course_proj\native_add\example\.dart_tool\flutter_build\50ebc546f2b6965eae53e58c91aaea8a\kernel_snapshot.d

**Comment by dcharkes** [comment]
Looks like your path gets truncated at 130 characters (it should in in .dill not .d). Does it work in a less deep folder?
