### ISSUE TITLE
Remove excessive uses of `asTypedList`

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/ffi#4]
Once `Pointer.load`/`Pointer.store` are optimized (https://github.com/dart-lang/sdk/issues/38172) we can remove some excessive uses of `Pointer.asTypedList`.

**Comment by Sunbreak** [comment]
Seems completed: https://github.com/dart-lang/ffi/blob/master/CHANGELOG.md#013-dev3

```
Replace use of deprecated asExternalTypedData with asTypedList.
```

**Comment by dcharkes** [comment]
Both Pointer.load/store and asTypedList have been optimized. So there's no need to replace one with another anymore.
