### ISSUE TITLE
flutter stable channel error

### ISSUE THREAD

**Issue by GanZhiXiong** [dart-lang/ffi#40]
Does it currently only support the flutter dev channel?

flutter stable channel error, as follow
```
Launching lib/main.dart on HUAWEI MT7 TL10 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/ganzhixiong/Documents/yilisheng/TemperatureSensor/test/camera_tutorial-master.zip Folder/camera_tutorial-master/android/settings.gradle' line: 15

* What went wrong:
A problem occurred evaluating settings 'android'.
> Could not read script '/Users/ganzhixiong/development/flutter/packages/flutter_tools/gradle/app_plugin_loader.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 516ms
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by dcharkes** [comment]
@GanZhiXiong I have not seen this error before. What Flutter version are you using? Could you provide the diagnostics and verbose logs? [See docs](https://flutter.dev/docs/resources/bug-reports).

**Comment by GanZhiXiong** [comment]
@dcharkes 
I'm glad to see your reply. Thank you. 

as follow
![image](https://user-images.githubusercontent.com/27394631/80466067-98baac80-896e-11ea-9440-efa8f7dbf533.png)

**Comment by dcharkes** [comment]
Can you please also provide the build log with verbose?

And is the code available so I can try to reproduce it locally?

**Comment by GanZhiXiong** [comment]
I will provide it to you later.
I think it's because ffi doesn't currently run on stable branches

**Comment by AnisovAleksey** [comment]
I use it in **stable** channel and it's work fine

**Comment by dcharkes** [comment]
Closing old issue, please reopen if you have further issues.
