### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by GanZhiXiong** [dart-lang/ffi#44]
- test
Position the cursor to line 19 in the figure below, option + enter
click“Run ‘toUtf8 ASCII in utf8...’”
The following error occurred
![image](https://user-images.githubusercontent.com/27394631/81424055-e9f54800-9187-11ea-903f-6aee3f1fa6b4.png)

- How do you run main.dart under example directory?

**Comment by GanZhiXiong** [comment]
![image](https://user-images.githubusercontent.com/27394631/81424382-70aa2500-9188-11ea-87bd-db7da10ce986.png)

**Comment by dcharkes** [comment]
With Dart on the command line:

```
$ cd your/path/to/ffi
$ pub get
...
$ pub run test
```

I'm not sure about the IDE integration. Which IDE is this? (I use VSCode with DartCode myself, which does not have a test runner integration.)

**Comment by dcharkes** [comment]
Closing old issue, please reopen if you still have issues.
