### ISSUE TITLE
how do you trouble shoot for this help please

### ISSUE THREAD

**Issue by marcpar** [dart-lang/ffi#53]
```
typedef RustIndyListPool = ffi.Pointer Function();

typedef IndyListPool = Function();

class Pool {
  static ffi.DynamicLibrary _lib;

  Pool() {
    _lib = load();
  }

  listPool() {
    final IndyListPool indyListPoolPointer = _lib
        .lookup<ffi.NativeFunction<RustIndyListPool>>('indy_list_pools')
        .asFunction();
    print(indyListPoolPointer());
    // final result = indyListPoolPointer.cast();
    // print(result);
  }
```

root@0954ea8ee28d:/srv/app# dart lib/src/dart_indy_base.dart 
lib/src/dart_indy_base.dart: Warning: Interpreting this as package URI, 'package:dart_indy/src/dart_indy_base.dart'.
Pointer<NativeType>: address=0x0

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x4c0
version=2.9.1 (stable) (Unknown timestamp) on "linux_x64"
pid=499, thread=512, isolate_group=(nil)((nil)), isolate=(nil)((nil))
isolate_instructions=0, vm_instructions=5584e08a8f80
Stack dump aborted because InitialRegisterCheck failed.
Aborted

**Comment by dcharkes** [comment]
Can you provide a repro for this?

When does this crash? You do get the print of the pool pointer (which is 0x0, which is usually a NULL/nullptr in C). Do you pass the null pointer back into C, and then the crash happens?

**Comment by dcharkes** [comment]
Closing old issue, please reopen if the issue persists.
