### ISSUE TITLE
Transform the nativePort to a Dart SendPort 

### ISSUE THREAD

**Issue by long1eu** [dart-lang/ffi#54]
I am able to get the pointer address of the SendPort using the `nativePort` field, but I'm not sure how to transform this back to a SendPort. The best I could do was to convert it into a `Dart_CObject` like this:

```dart
final Dart_CObject port = Pointer<Dart_CObject>.fromAddress(portAddress).ref;
```

Is there a way to reconstruct the dart object based on that pointer address. I know this is mainly used in the C part, but in my use case the C part is only the glue between two Isolates that can't be created directly in dart.

**Comment by long1eu** [comment]
Here is a simplified example. The only difference in this case is that I can't SendPort as the argument of the `_second` method, it must be throw a pointer address.

```dart
import 'dart:isolate';
import 'dart:ffi';

Future<void> main() async {
  final ReceivePort receivePort = ReceivePort();
  final int port = receivePort.sendPort.nativePort;
  print(port.hashCode);

  Isolate.spawn(_second, port);
  receivePort.listen((message) {
    print(['received on ${Isolate.current.hashCode}']);
  });
}

Future<void> _second(int message) async {
  print(['started with port $message']);
  final Dart_CObject ref = Pointer<Dart_CObject>.fromAddress(message).ref;
}
```

**Comment by dcharkes** [comment]
Hey Razvan,

It is not possible to construct a SendPort from an integer address in Dart
at the moment.

The normal operation is to send a SendPort as a message to the other
isolate.
https://api.flutter.dev/flutter/dart-isolate/SendPort-class.html

Let me try to understand your use case. How are you constructing your
second isolate? Can you set up the isolate communication in the usual way
there?

Kind regards,

* •  **Daco Harkes*
* •  *Software Engineer
* •  *dacoharkes@google.com

**Comment by long1eu** [comment]
Unfortunately I can't construct it the normal way. They way I do it is
through FlutterEngine in Java. That creates a new isolate and I am able to
register plugins and call the dart _second method. But at this stage I want
to be able to communicate with the main Isolate directly and not go back to
Java an back to dart.

**Comment by dcharkes** [comment]
Hi Razvan,

Please file a feature request on
https://github.com/dart-lang/sdk/labels/library-ffi explaining your use
case and we'll take a look at it. Please tag me in the issue.

Kind regards,

* •  **Daco Harkes*
* •  *Software Engineer
* •  *dacoharkes@google.com

**Comment by dcharkes** [comment]
Issue solved in https://github.com/dart-lang/sdk/issues/43877#issuecomment-714253574.

**Comment by long1eu** [comment]
@dcharkes thanks
