### ISSUE TITLE
What is the best practice of handling dynamic library file? 

### ISSUE THREAD

**Issue by pedia** [dart-lang/ffi#56]
Since a library of ffi always contain a dynamic library(binary, not exists in system folder), 
So question: 
- Where to place this library?
- How to handle this library in caller?

Without copy the library to current folder, the error like:

> Dart FFI fails loading dynamic library in MacOS

Code in ffi library:
```dart
String _getPath() {
  var path = 'libzstd.so';
  if (Platform.isMacOS) {
    path = 'libzstd.dylib';
  }
  if (Platform.isWindows) {
    path = 'zstd.dll';
  }
  return path;
}

ZStd _lib;

ffi.DynamicLibrary _openLibrary() {
  return ffi.DynamicLibrary.open(_getPath());
}
```

How to handle file `libzstd.dylib`?

The source is [zstd_ffi](https://github.com/finlutter/zstd_ffi)

Thanks.

**Comment by dcharkes** [comment]
Hi @pedia,

What is the error message?

And are you running `dart` from the command line or is this a Flutter desktop application?

**Comment by pedia** [comment]
The error is: not found the laibrary.

Yes, running from desktop of mac

**Comment by dcharkes** [comment]
Can you try with the full path?

If you use a relative path like this it searches for it relative to the `dart` executable.

You can construct a full path by using the path of the `.dart` file you're running with https://api.dart.dev/stable/2.10.3/dart-io/Platform/script.html and from there navigate to the file.

(You can also use https://api.dart.dev/stable/2.10.3/dart-io/FileSystemEntity/existsSync.html to check if the file really exists before doing `DynamicLibrary.open`.)

**Comment by pedia** [comment]
I do not think full path is a great idea.

Is it possible copy dependency shared library to console/App folder in `pub get`?

Maybe location of Android:
```
android/src/main/jniLibs/arm64-v8a/
android/src/main/jniLibs/x86/
```

**Comment by jpnurmi** [comment]
I don't mean to promote an article of mine, but I just wanted to mention that I recently wrote up about (ab)using Flutter's build system for building and deploying C libraries: https://medium.com/flutter-community/build-and-deploy-native-c-libraries-with-flutter-cc7531d590b5. Even if you prefer to keep your package pure Dart and don't want to pull in Flutter as a dependency, the parts about deployment structure on each platform may help.

**Comment by Sunbreak** [comment]
Dart wrapper for libusb: https://github.com/woodemi/libusb.dart

Flutter plugin using libusb.dart: https://github.com/woodemi/quick_usb
