### ISSUE TITLE
Bridge between dart:io and FILE

### ISSUE THREAD

**Issue by listepo** [dart-lang/ffi#57]
It would be nice to be able to create a file in `dart:io` and pass it as a pointer to a function in `C lang`.
For example where it is needed: 
https://www.postgresql.org/docs/9.1/libpq-control.html
```
void PQtrace(PGconn *conn, FILE *stream);
```
@dcharkes is it possible?

**Comment by dcharkes** [comment]
Currently we don't expose any `dart:io` internals through FFI. What is your use case for not opening the file natively?

**Comment by listepo** [comment]
I just use [ffigen](https://github.com/dart-lang/ffigen) for [libpq](https://www.postgresql.org/docs/13/libpq.html) and I understand that I can create a helper(in C lang and add ffi bindings) that would implement a part of the dart:io. But I do not know if it's a good idea.

**Comment by listepo** [comment]
I try to write a postgres client for dart with official libpq. So I would like to have something like `void trace(File file)` for the end-user

**Comment by dcharkes** [comment]
While file handles are OS-specific, all of them are `int`s, so it would be technically possible to expose these file handles through FFI.

However, then we get a question about resource ownership. The `dart:io` `File` class does not support transferring ownership (who should close the file). As such, when an object of type `File` is garbage collected, the file handle gets closed automatically. If a file handle is passed to native code, it should not be closed until native code is done using it, or the native code will crash. This means you'll have to create a closure that invokes `File.close`, and make sure to invoke that closure when you're no longer using the file in native code. The closure would hold on to the File object which prevents it from being garbage collected.

If we decide to introduce something like this in the future, we would spend considerable time thinking about a good resource lifetime management solution. Just exposing file handles in `dart:ffi` would lead to an error prone API.

> I just use [ffigen](https://github.com/dart-lang/ffigen) for [libpq](https://www.postgresql.org/docs/13/libpq.html) and I understand that I can create a helper(in C lang and add ffi bindings) that would implement a part of the dart:io. But I do not know if it's a good idea.

I think adding a helper function in C is the right solution for now.

**Comment by listepo** [comment]
@dcharkes thanks

**Comment by JimTompkins** [comment]
Hi,
I'm trying to do something similar to the original question above:

I used ffigen to create bindings for a library:

```
int BASS_SampleLoad(
    int mem,
    ffi.Pointer<ffi.Void> file,
    int offset,
    int length,
    int max,
    int flags,
  ) {
    return _BASS_SampleLoad(
      mem,
      file,
      offset,
      length,
      max,
      flags,
    );
  }
```

I'd like to call this function as follows:

```
                      File audioFile = await _localFile;
                      ffi.Pointer<ffi.Void> filePointer = audioFile.cast<ffi.Void>();
                      cowbell = bass.BASS_SampleLoad(
                        0,      // mem: use file instead of memory
                        filePointer,   // *file: file pointer
                        0,      // offset: use file from the start
                        0,      // length: use entire file
                        16,     // max: maximum number of simultaneous playbacks
                        0       // flags: no flags set
                        );
```
but there is no cast method for the File class.

Has there been any change in this situation since the original issue was posted?  

Any suggestions greatly appreciated!

**Comment by dcharkes** [comment]
> Has there been any change in this situation since the original issue was posted?

No. My previous reply pertaining to ownership still stands. Opening the file in C with a helper is the solution.

**Comment by JimTompkins** [comment]
I'm trying to make a C helper file that will do the file I/O so I wrote this code:

```
// C file utilities
// openFile: open a file and return a pointer to it
// closeFile: close a file

// this next line is recommended by [docs.flutter.dev](http://docs.flutter.dev/) article 
// Binding to natiove iOS code using dart:ffi, but it gives an error:
//    Could not build the precompiled application for the device.
//    Parse Issue (Xcode): Expected identifier or '('
//    /Users/jimtompkins/git/flutter_bass/src/file_utils.c:3:7
//extern "C" /* <= C++ only */ __attribute__((visibility("default"))) __attribute__((used))

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdbool.h>

char* get_string(void) {
  char* test = "test";
  char* test_m = malloc(strlen(test));
  strcpy(test_m, test);
  return test_m;
}

FILE *openFile(char *filename)
  {
    FILE *fp;
    fp = fopen(filename, "r");
    return(fp);
  }

void closeFile(FILE *fp) 
{
    fclose(fp);
    return;
}
```
And added it to the Xcode project.  Xcode compiles it without errors but doesn't seem to produce a .a file or a framework.

I get this error message when I call a function from the C file:
`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'file_utils.framework/file_utils': dlopen(file_utils.framework/file_utils, 1): image not found`

How do you tell Xcode to make a .a file? or a framework?

When you include a C source file, should it be a dynamic or static library?  I tried changing from DynamicLibrary.open to DynamicLibrary.executable but I get the same error message.

Thanks for any hints.

**Comment by JimTompkins** [comment]
Yes, I used the C file in the template plugin and it builds but now throws a runtime error:

`Error:
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'Pointer<__sFILE>' is not a subtype of type 'Pointer<Void>' in type cast
`

Here is the ffi_gen generated code for the library function fopen:
`ffi.Pointer<FILE> fopen(
    ffi.Pointer<ffi.Char> __filename,
    ffi.Pointer<ffi.Char> __mode,
  ) {
    return _fopen(
      __filename,
      __mode,
    );
  }

  late final _fopenPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<FILE> Function(
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>>('fopen');
  late final _fopen = _fopenPtr.asFunction<
      ffi.Pointer<FILE> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();
`

fopen returns a Pointer<FILE>.  The function I'm trying to call needs a file pointer as a Pointer<Void>:

`int BASS_SampleLoad(
    int mem,    ffi.Pointer<ffi.Void> file,
    int offset, int length, int max, int flags,
  ) {
    return _BASS_SampleLoad(
      mem, file, offset, length, max, flags,
    );
  }

  late final _BASS_SampleLoadPtr = _lookup<
      ffi.NativeFunction<
          HSAMPLE Function(BOOL, ffi.Pointer<ffi.Void>, QWORD, DWORD, DWORD,
              DWORD)>>('BASS_SampleLoad');
  late final _BASS_SampleLoad = _BASS_SampleLoadPtr.asFunction<
      int Function(int, ffi.Pointer<ffi.Void>, int, int, int, int)>();
`
I try to cast the result of fopen to ffi.Pointer<ffi.Void>.

`ffi.Pointer<ffi.Void> mp3File = fileUtils.fopen(
        fileName.toNativeUtf8().cast<ffi.Char>(),
        "r".toNativeUtf8().cast<ffi.Char>())
    as ffi.Pointer<ffi.Void>;
cowbellSample = bass.BASS_SampleLoad(0,mp3File,0,0,16,0);`

But get the error.  Without the cast, there is a build error:

` lib/main.dart:131:65: Error: A value of type 'Pointer<__sFILE>' can't
be assigned to a variable of type 'Pointer<Void>'.
- 'Pointer' is from 'dart:ffi'.
- '__sFILE' is from    
'package:flutter_bass/file_utils/generated_bindings.dart' ('../lib/file_utils/generated_bindings.dart').
- 'Void' is from 'dart:ffi'.
ffi.Pointer<ffi.Void> mp3File = fileUtils.fopen(`

How can I convert the output of fopen to an ffi.Pointer<ffi.Void>?

Thanks for your patience!

**Comment by JimTompkins** [comment]
The repo is on [Github](https://github.com/JimTompkins/flutter_bass)

**Comment by dcharkes** [comment]
Please file new issues or ask questions on stackoverflow.

> How can I convert the output of fopen to an ffi.Pointer<ffi.Void>?

```dart
final Pointer< __sFILE> p = // ...
final Pointer<Void> p2 = p.cast(); // type argument to cast inferred as  p.cast<Void>();
```
