### ISSUE TITLE
[pigeon] redirect pigeon resources to ffi - cross post

### ISSUE THREAD

**Issue by bsutton** [dart-lang/ffi#58]
As this issue pertains to both pigeon and ffi I've add a duplicate issue here as well.

The original issue is:
https://github.com/flutter/flutter/issues/70254

@gaaclarke 

So I want to express what I'm sure will be a controversial opinion.

The nub of the idea is to drop the pigeon project and instead focus all resources onto ffi.

Background:

I'm the author of the Sounds project:
https://pub.dev/packages/sounds

One of the big issues we are grappling with is having to be across four development languages:
Dart
Java
Objective-C
Swift

This is a significant problem for getting resources applied to the project and has the core team bumbling around with languages that they just aren't familiar with.

We have been experimenting with ways to make the project easier to maintain.

The first thing we looked at was converting all of the objective-c to swift as swift is a simpler language and more 'dart' like than objective-c.
This helped some but we still had bits of objective-c left in the code for bridging purposes and we are still not swift experts (or even novices).

Next we had a look at pigeon for a couple of reasons.
1) we liked that it largely managed channels for us.
2) we hoped it would take care of some of the bridging code (not so much).
3) we liked the concept of a federated model (yes not pigeon specific but it helped).

We did an initial implementation with pigeon and the process actually helped us improve our platform api but it did nothing to reduce the no. of languages that we needed to support.

So we are now looking at ffi and dart-native.
https://pub.dev/packages/dart_native

The dart-native project is useful but still very primitive however its clear (to our team at least) that using ffi is a much better path than pigeon.

Once we complete the ffi work we should go close to eliminating all objective-c, swift and java code.
This will make our project much simpler to maintain and should make it easier to get additional contributors.

The biggest stumbling block is that, whilst dart-native, helps we are still having to implement ffi wrappers for large parts of the ios api (and currently all of the java api).

My view is that pigeon is really just a stop gap measure and long term I don't see pigeon being a part of the dart ecosystem.

As such I'm arguing that rather than wasting resources on a stop gap measure those resources would be better placed on completing ffi, improving the documentation and providing a complete set of ffi mappings for the ios and android apis.

I understand that this will be a large task but it is one that could be rolled out progressively and one that the community could easily contribute to by backfilling apis that they need them.

# Summary

* stop work on pigeon
* commence work on providing a full set of dart api wrappers for the android and ios libraries.
* improve the ffi documentation with more worked examples.
* Encourage the community to contribute api wrappers.

**Comment by gaaclarke** [comment]
The Dart team isn't familiar with the Pigeon or with the difficulties of using FFI with Flutter.  You'll probably have better luck filing issues here that are specific to Dart FFI, applicable to Flutter users and someone creating a command-line Dart program for example.

When you have recommendations about how Flutter could make FFI integration better, outside of Pigeon, you should file an issue with that information in the Flutter database.

**Comment by dcharkes** [comment]
Closing this issue. If you have specific recommendations for `dart:ffi` please file an issue in https://github.com/dart-lang/sdk/labels/library-ffi, and if you have specific recommendations for `package:ffi` please file a new issue in this repo.
