### ISSUE TITLE
Allow Utf8 usage without cast

### ISSUE THREAD

**Issue by vaind** [dart-lang/ffi#6]
[This example](https://github.com/dart-lang/samples/blob/master/ffi/structs/structs.dart) seemed to allow passing to C and reading from C without casts, by defining an FFI function as follows:

```
typedef reverse_func = ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> str, ffi.Int32 length);
...
// used as:
final reversedMessage = Utf8.fromUtf8(reverse(Utf8.toUtf8('backwards'), 9));
```

That doesn't work with the current version of the `Utf8.toUtf8` and `fromUtf8`. It's necessary to use `Pointer<Uint8>` in the function definition with as well as appropriate casts when calling/receiving. The error when using the signature as above is `Error: Expected type 'Pointer<Utf8> Function()' to be 'Pointer<Uint8> Function()'`

As this is repeated in all the calls, it would be nice if we could get rid of the casts altogether (which seemed to have worked in the given example).

The difference seems to be
```
class Utf8 extends ffi.Struct<Utf8> {
  @ffi.Uint8() // this
```

**Comment by mkustermann** [comment]
@dcharkes @sjindel-google

**Comment by sjindel-google** [comment]
@vaind Can you please share the code where you call `asFunction`/`lookupFunction`?

**Comment by vaind** [comment]
Does this diff help? It was an attempt to get rid of the casts. 

https://github.com/objectbox/objectbox-dart/commit/db1454d6b0fbb5753df04f6d3f33e59908b44757

**Comment by sjindel-google** [comment]
I checked out your code but I couldn't find the `reverse` function?

**Comment by vaind** [comment]
The reverse function from the description of this comment is from the dart FFI example repo linked in the original post. We're not using that function, I just referred to it hoping you'd be aware of it and it would be easier to understand than talking about our actual code (as linked in the previous comment)

**Comment by vaind** [comment]
This is now possible with ffi 0.1.3
