### ISSUE TITLE
FFI allocate returns uninitialized memory

### ISSUE THREAD

**Issue by timsneath** [dart-lang/ffi#69]
`malloc()` and `HeapAlloc()` (in POSIX and Windows systems, respectively) both return uninitialized memory. When used to initialize memory on the heap that will be used by Dart, the results are therefore indeterminate. If a struct allocated through this route that is later passed to to a native library without fully initializing every field, it will give unpredictable results. (And see https://matt.sh/howto-c#_never-use-malloc).

I'd therefore like to suggest that we make changes to the following function:
https://github.com/dart-lang/ffi/blob/31352979f261f7c6ea88fa0a2cfb0fdd004c38fb/lib/src/allocation.dart#L46-L58

On Windows, passing [the `HEAP_ZERO_MEMORY` flag](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc) (instead of `0`), will initialize the memory returned from the heap. On POSIX-style platforms, [the `calloc()` function](https://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html) has the same effect.

**Comment by dcharkes** [comment]
Good suggestion!

We're revamping the memory allocation API, requiring people to pass in an `Allocator` into `allocate` ( https://github.com/dart-lang/sdk/issues/44621).

We should add a `CallocAllocator` to this package (https://github.com/dart-lang/ffi/commit/01a67e972e506ffd877737bfb61072c0f0c5e23d):

```dart
/// Manages memory on the native heap.
///
/// Initializes newly allocated memory to zero.
///
/// For POSIX-based systems, this uses calloc and free. On Windows, it uses
/// HeapAlloc with [HEAP_ZERO_MEMORY] and HeapFree against the default public
/// heap.
class CallocAllocator implements Allocator {
  const CallocAllocator();

  /// Allocates zero-intialized memory on the native heap.
  ///
  /// For POSIX-based systems, this uses malloc. On Windows, it uses HeapAlloc
  /// against the default public heap.
  ///
  /// Throws an ArgumentError on failure to allocate.
  // TODO: Stop ignoring alignment if it's large, for example for SSE data.
  @override
  Pointer<T> allocate<T extends NativeType>(int numBytes, {int? alignment}) {
    Pointer<T> result;
    if (Platform.isWindows) {
      result = winHeapAlloc(processHeap, /*flags=*/ HEAP_ZERO_MEMORY, numBytes)
          .cast();
    } else {
      result = posixCalloc(numBytes, 1).cast();
    }
    if (result.address == 0) {
      throw ArgumentError('Could not allocate $numBytes bytes.');
    }
    return result;
  }

  /// Releases memory on the native heap.
  ///
  /// For POSIX-based systems, this uses free. On Windows, it uses HeapFree
  /// against the default public heap. It may only be used against pointers
  /// allocated in a manner equivalent to [allocate].
  ///
  /// Throws an ArgumentError on failure to free.
  ///
  // TODO(dartbug.com/36855): Once we have a ffi.Bool type we can use it instead
  // of testing the return integer to be non-zero.
  @override
  void free(Pointer pointer) {
    if (Platform.isWindows) {
      if (winHeapFree(processHeap, /*flags=*/ 0, pointer) == 0) {
        throw ArgumentError('Could not free $pointer.');
      }
    } else {
      posixFree(pointer);
    }
  }
}

const calloc = CallocAllocator();
```

**Comment by dcharkes** [comment]
https://github.com/dart-lang/ffi/pull/72
