### ISSUE TITLE
malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by mhliebano** [dart-lang/ffi#70]
Hi, i have this error, my code, implement SDLDart binding:

In C++:

`     
     
     typedef struct SDL_RendererInfo {
       const char *name;           /**< The name of the renderer */

         Uint32 flags;               /**< Supported ::SDL_RendererFlags */
     
        Uint32 num_texture_formats; /**< The number of available texture formats */

         Uint32 texture_formats[16]; /**< The available texture formats */

         int max_texture_width;      /**< The maximum texture width */

         int max_texture_height;     /**< The maximum texture height */

     } SDL_RendererInfo;

`

StructFile in dart

`
    
     import 'dart:ffi';
     import 'package:ffi/ffi.dart';

    class RendererStruct extends Struct {
       Pointer<Utf8> name;
      @Uint32()
       int flags;
       @Uint32()
       int num_texture_formats;
       Pointer<Int32> texture_formats;
      @Uint32()
       int max_texture_width;
      @Uint32()
       int max_texture_height;
    factory RendererStruct.allocate(
      Pointer<Utf8> name,
      int flags,
      int texture_formats,
      Pointer<Int32> num_texture_formats,
      int max_texture_width,
      int max_texture_height) {
    return allocate<RendererStruct>().ref
      ..flags
      ..name
      ..texture_formats
      ..num_texture_formats
      ..max_texture_height
      ..max_texture_width;
    }
   }

`

And try:

`
   
 Pointer< RendererStruct > info = allocate< RendererStruct >(count: 1);

`

Console:
malloc(): unsorted double linked list corrupted

any idea?

the code is aviable in https://github.com/mhliebano/dartSDL

**Comment by dcharkes** [comment]
@mhliebano for questions regarding your own code please ask questions on StackOverflow.

If there is a problem with `dart:ffi` or `package:ffi` please provide a minimal example (either snippets or a GitHub repository).

Regarding your question. where does `unsorted double linked list corrupted` come from? C or Dart? If C, where is the source code for C? You can debug native code by using `gdb` on the `dart` executable, you'll be able to set breakpoints in your `.so` file to debug what is going on.
