### ISSUE TITLE
Release api/allocator-opaque to pub

### ISSUE THREAD

**Issue by simolus3** [dart-lang/ffi#71]
I'm trying to migrate my packages to remove empty structs and non-constant type arguments for `sizeOf`. To avoid dependency overrides that I'd have to push down to users, it would be great to have a pub-version of `ffi` that contains the allocator apis.

I couldn't find an existing issue for this so I'm creating this one. Can the `api/allocator-opaque` branch be merged and released to pub?

**Comment by dcharkes** [comment]
We've published https://pub.dev/packages/ffi/versions/0.3.0-nullsafety.0 which requires `2.12.0-265.0.dev` or greater

The last Dart dev release is `2.12.0-259.0.dev`, so the package cannot be used yet. (I'm not aware of anyone on Dart master, building their own SDK.)

In Flutter-master is at Dart `2.12.0-276.0.dev`, so this can be used on Flutter master.

**Comment by dcharkes** [comment]
I also need to release a version with SDK constraint `2.12.0-259.X.beta` after https://github.com/flutter/flutter/issues/75134 (and possibly https://github.com/dart-lang/sdk/issues/44822) have been cherry picked.

This version would wrongly mark `2.12.0-260.0.dev` - `2.12.0-264.0.dev` as valid SDK versions, but there is not really a way around that.

**Comment by dcharkes** [comment]
We've released https://pub.dev/packages/ffi/versions/0.3.0-nullsafety.1 which Dart `2.12.0-259.8.beta` or greater.

Current beta release is `2.12.0-259.1.beta`, so this will be available in the next beta release.

This Dart version including cherry pick for flutter/engine#23954 will be available in the next Flutter beta release (in flutter/engine#24142). Note that without this cherry pick `Allocator.call` throws a `NoSuchMethodError`, which is the reason we cannot release for Dart `2.12.0-259.1.beta`.

**Comment by dcharkes** [comment]
https://pub.dev/packages/ffi/versions/0.3.0-nullsafety.1 is available in the current Dart/Flutter beta.
