### ISSUE TITLE
Run in release mode, compile error report `Undefined symbol: _rust_greeting`

### ISSUE THREAD

**Issue by Aaron009** [dart-lang/ffi#75]
I know this problem has been raised by many people, but I also followed the solution they said, but it did not solve the problem.

```shell
Flutter 1.25.0-8.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5d36f2e7f5 (3 weeks ago) • 2021-01-14 15:57:49 -0800
Engine • revision 7a8f8ca02c
Tools • Dart 2.12.0 (build 2.12.0-133.7.beta)
```

I first clone the project by executing the command:

```shell
git clone https://github.com/brickpop/flutter-rust-ffi
```

Then when debugging, an error occurred, I deleted the project IOS folder and executed the following command:

```shell
flutter create .
```

At this time, the debugging operation was successful, but it failed when it was released. The error screenshot is as follows[![1.png](https://i.postimg.cc/MG7c88hp/1.png)](https://postimg.cc/Z9qYrXbG)

Then, I found the following information to solve this problem, but it didn't work after trying.

https://github.com/brickpop/flutter-rust-ffi/issues/7

https://github.com/dart-lang/ffi/issues/41

https://github.com/shekohex/flutterust/issues/17

1. ```shell
   In Xcode, go to Target Runner > Build Settings > Strip Style.
   Change from All Symbols to Non-Global Symbols.
   ```
	 [![2.png](https://i.postimg.cc/ZRgz7WVB/2.png)](https://postimg.cc/bDQ5dwXp)
	 Test result: No
2. https://github.com/dart-lang/ffi/issues/41#issuecomment-751496383
	 enable testability.
	 [![3.png](https://i.postimg.cc/d3jPq5Jd/3.png)](https://postimg.cc/D40Y6dJy)
	 Test result: No

**Comment by brickpop** [comment]
https://github.com/brickpop/flutter-rust-ffi/issues/16 might be the one relevant here.

The `STRIP_STYLE` setting may not be needed on the Flutter project, but on the plugin project you export (Pod spec file)

**Comment by Aaron009** [comment]
> [brickpop/flutter-rust-ffi#16](https://github.com/brickpop/flutter-rust-ffi/issues/16) might be the one relevant here.
> 
> The `STRIP_STYLE` setting may not be needed on the Flutter project, but on the plugin project you export (Pod spec file)

### I found the solution:

#### Step 1:
When publishing, it must be tested on a real machine, otherwise it will prompt that "Module'mylib" is not found

#### Step 2:
Find "Architectures" in "Build Seetings" and make the following modifications
[![1.png](https://i.postimg.cc/Rh8k2Pf9/1.png)](https://postimg.cc/y3mpZyvr)

XCode's default "standard architecture (arm64, armv7)" and ".a" files do not contain "armv7", and the new version of Rust has eliminated armv7.

**I am a little depressed. Before I went to bed, I could still publish my work normally, but when I was preparing for the `Pull Request` the next day, a new problem appeared.**

After compilation, after the new version is released, the application will be grayed out.

**Comment by brickpop** [comment]
Apple is currently supporting arm64 and x86_64 only. If your app is targeting iOS 9 or earlier, then you'd need to compile the static library for armv7, but the amount of people still using iphone 5 in 2021 is negligible I think.

The greyed out problem is new to me :(

**Comment by shekohex** [comment]
Hey @Aaron009 if this solution worked well for you, could you please add these steps to the [flutterust](https://github.com/shekohex/flutterust) `README`? it would be appreciated

**Comment by Aaron009** [comment]
@brickpop @brickpop 
Regarding the gray screen of running App after release, I solved it by recreating the Flutter plug-in project.
