### ISSUE TITLE
Conditional type annotation

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffi#77]
# Background

I'm working on Dart wrapper via `dart:ffi` for `libusb`: https://github.com/woodemi/libusb.dart

# Problem

`libusb_linux.dart` is identical to `libusb_windows.dart` while `libusb_mac.dart` is a little different

- Windows/Linux

```dart
class timeval extends ffi.Struct {
  // ...
  @ffi.Int64()
  int tv_usec;
}
```

- macOS

```dart
class timeval extends ffi.Struct {
  // ...
  @ffi.Int32()
  int tv_usec;
}
```

Calling the APIs requires `import 'packages:libusb/libusb_windows.dart` for Windows, `libusb_macos.dart` for macOS and `libusb_linux.dart` for Linux

https://github.com/woodemi/libusb.dart/blob/afabb0fb3deeef240b6a893cf79a92cf1aa878f8/example/listdevs.dart#L7-L10

```dart
// git update-index --assume-unchanged example/listdevs.dart
// import 'package:libusb/libusb_windows.dart';
// import 'package:libusb/libusb_macos.dart';
// import 'package:libusb/libusb_linux.dart';
```

It's quite cumbersome and error prone

# Feature Request

Could we support something like 

```dart
class timeval extends ffi.Struct {
  // ...
  @ffi.Int64() if (Platforms.isMac) @ffi.Int32()
  int tv_usec;
}
```

**Comment by Sunbreak** [comment]
BTW, `Conditional Import` via `Platforms.isWindows/isMacOS/isLinux` would work as well

```dart
import 'timeval64.dart if (Platforms.isMac) timeval32.dart';
```

However, `Conditional Import` is only available for Dart SDK library, i.e. `dart.library.io`/`dart.library.js`/`dart.library.html`/`dart.library.ffi` as far as I know

**Comment by dcharkes** [comment]
Yes, we are tracking this here: https://github.com/dart-lang/sdk/issues/42563.

**Comment by dcharkes** [comment]
I'll go ahead and close this issue, as this is not a `package:ffi` issue, but rather a `dart:ffi` feature, and we're already tracking it.
