### ISSUE TITLE
Migrate package:ffi in g3

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffi#82]
We need to migrate the use of this package in g3, related to breaking change https://github.com/dart-lang/sdk/issues/44621.

1. Have a package version with `allocate` and `free` (but deprecated), and the `Allocator` API. (https://github.com/dart-lang/ffi/pull/79 + fix in https://github.com/dart-lang/ffi/pull/81)
2. Roll that into the Dart SDK with DEPS.
3. Wait for Dart SDK->g3 roll.
4. Migrate g3.
5. Have a package version without `allocate` and `free`.
6. Roll that into the Dart SDK with DEPS.
7. Wait for Dart SDK->g3 roll.
8. Do the Dart SDK changes that turn deprecation warnings into errors on `sizeOf<T>` and empty structs. (https://github.com/dart-lang/sdk/issues/44621 and https://github.com/dart-lang/sdk/issues/44622)

**Comment by mit-mit** [comment]
cc @natebosch can you please review this list of steps and see if this sounds reasonable for rolling a package in g3 past a breaking change in the SDK?

**Comment by natebosch** [comment]
Yes, this all sounds reasonable.

Steps 3 and 7 can be compressed if we need to. There is a tool I can share internally which we can use to roll a package in g3 before the SDK sync happens.

**Comment by dcharkes** [comment]
The final steps have landed
6. https://dart-review.googlesource.com/c/sdk/+/185141
8. https://dart-review.googlesource.com/c/sdk/+/178200

g3 is now up to date with 1.0.0
