### ISSUE TITLE
Empty structs are undefined behavior

### ISSUE THREAD

**Issue by jackselvam** [dart-lang/ffi#85]
Flutter 1.27.0-5.0.pre.92 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2c5c509486 (19 hours ago) • 2021-02-20 15:11:04 -0500
Engine • revision b793775d2a
Tools • Dart 2.13.0 (build 2.13.0-52.0.dev)

Error:
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf8.dart(23,7): error G09587AA0: Struct 'Utf8' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]
/C:/Users/Jack%20Selvam/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/ffi-0.1.3/lib/src/utf16.dart(16,7): error G09587AA0: Struct 'Utf16' is empty. Empty structs are undefined behavior. [D:\Project\SKS_Software\skssoftware\build\windows\flutter\flutter_assemble.vcxproj]

Unable to build or run windows desktop app

**Comment by dcharkes** [comment]
Hi @jackselvam,

On the master branch, support for empty structs has been removed. You should update `package:ffi` to version 1.0.0.

See https://github.com/flutter/flutter/issues/76485.

Could you please post your `pubspec.yaml` and the output of `pub deps`?

**Comment by dcharkes** [comment]
Dart 2.13 is now in beta. This is expected behavior next stable release.

@jackselvam if you still have the issue please reopen.
