### ISSUE TITLE
[Feature] `use` like function for temporory native malloc/calloc object

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffi#86]
It is quit easy to forget to free memory from `toNativeUtf8` and `toNativeUtf16`

https://github.com/Sunbreak/logic_conf.dart/commit/956ac5afe23e51d24854329007bd63a6d518d560

```diff
-    var descriptor = _libc.open2(path.toNativeUtf8().cast(), O_RDWR);
+    var nativeUtf8 = path.toNativeUtf8();
+    var descriptor = _libc.open2(nativeUtf8.cast(), O_RDWR);
+    malloc.free(nativeUtf8);
```

Could we have some Kolin's `use`-like statement?

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/use.html

```kt
FileWriter("test.txt")
  .use { w -> w.write("something") }
```

Or similiar ones:

- Java's try-with-resource: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
- C# using: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement

**Comment by Sunbreak** [comment]
Related: https://github.com/dart-lang/sdk/issues/32486

**Comment by dcharkes** [comment]
Hey, please take a look at the `Pool`: https://github.com/dart-lang/sdk/blob/master/samples/ffi/resource_management/pool_sample.dart#L24-L31

```dart
  // To ensure resources are freed, wrap them in a [using] call.
  using((Pool pool) {
    final p = pool<Int64>(2);

    // Do something with p.

    // p is automatically `free`d at the end of this scope.
  });
  ```

Please let me know if you find that sample useful, I could merge it to this package.

**Comment by Sunbreak** [comment]
It helps a lot. https://github.com/Sunbreak/logic_conf.dart/pull/8

I'll appreciate if we could merge `Pool` to `package:ffi`

**Comment by Fox32** [comment]
Done by #103?

**Comment by dcharkes** [comment]
Indeed.

**Comment by hacker1024** [comment]
Is this documented anywhere? I had to go searching through issues to find this feature. I  didn't think to look at the API reference because the README points to another website.

Perhaps a brief overview of the features provided by this package could be added to the README?
