### ISSUE TITLE
Failed to lookup symbol (dlsym(RTLD_DEFAULT, calloc.free): symbol not found))

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/ffi#88]
Hi,

it seems I found a bug in `allocation.dart` because I get the exception above when calling `calloc.free` on a Mac, probably on any non Windows platform because this is how the `PossixFree` looks like:

```
final PosixFree posixFree = stdlib.lookupFunction<PosixFreeNative, PosixFree>('calloc.free');
```

if I change the `calloc.free` to free it works.

Cheers
Thomas

**Comment by dcharkes** [comment]
Maybe you locally search-replaced it in `package:ffi` source code as well? Because on this repo the code is exactly as you say it should be:

https://github.com/dart-lang/ffi/blob/f3346299c55669cc0db48afae85b8110088bf8da/lib/src/allocation.dart#L23-L26

**Comment by escamoteur** [comment]
UUh, you might be right, sorry
