### ISSUE TITLE
Question: How do I allocate a struct

### ISSUE THREAD

**Issue by nailuj29gaming** [dart-lang/ffi#90]
When I try to create an `Allocator`, it doesn't work. How can I allocate my struct from dart?

**Comment by dcharkes** [comment]
Can you be more specific?

**Comment by nailuj29gaming** [comment]
Where is `calloc`? I can't seem to find it

**Comment by nailuj29gaming** [comment]
@dcharkes `calloc` is undefined

**Comment by nailuj29gaming** [comment]
I see I needed the `ffi` pub package
