### ISSUE TITLE
Question: Convert `Pointer<Int8>` to `Pointer<Utf8>`

### ISSUE THREAD

**Issue by nailuj29gaming** [dart-lang/ffi#91]
When I use `ffigen`, it outputs code that takes pointers to `Int8` for strings, but I would like pointer to `Utf8` instead, as it can be easily converted to and from Dart strings.

**Comment by dcharkes** [comment]
This is tracked in package:ffigen (https://github.com/dart-lang/ffigen/issues/72), not package:ffi. Please reply your suggestion in that issue. Closing this one.
