### ISSUE TITLE
Trying to access pointer value from the Struct closes the application

### ISSUE THREAD

**Issue by kirill-21** [dart-lang/ffi#96]
I have a struct
```
class MODULEINFO extends Struct {
  external Pointer lpBaseOfDll;
  @Uint32()
  external int sizeOfImage;
  external Pointer entryPoint;
}
```
And a function
```
static getModuleInformation(int hProcess, int hModule) {
    final _getModuleInformation = _psapi.lookupFunction<
        Int32 Function(IntPtr hProcess, IntPtr hModule, Pointer<MODULEINFO> lpmodinfo, Int32 cb),
        int Function(int hProcess, int hModule, Pointer<MODULEINFO> lpmodinfo, int cb)>('GetModuleInformation');

    final mi = calloc<MODULEINFO>();
    final int dwSize = sizeOf<MODULEINFO>();

    int f = _getModuleInformation(hProcess, hModule, mi, dwSize);
    print(f); // Function succeeded with result 1

    print(mi.ref.lpBaseOfDll.cast<Int32>().elementAt(0).value); // Application just closes 
  }
```

When i try to print a value from the struct - application crashes without any errors. Am i doing something wrong or it's a bug?

**Comment by dcharkes** [comment]
Hi!

What does `print(mi.ref.lpBaseOfDll)` print? If that is an address that is not allocated or it is `0x0` (nullptr) and you're trying to access that, the application crashes with a segmentation fault because you're trying to access memory that your application has not allocated.

**Comment by kirill-21** [comment]
> Hi!
> 
> What does `print(mi.ref.lpBaseOfDll)` print? If that is an address that is not allocated or it is `0x0` (nullptr) and you're trying to access that, the application crashes with a segmentation fault because you're trying to access memory that your application has not allocated.

... address at 0x75190000 ...

**Comment by mraleph** [comment]
Is `hProcess` pointing to your current process or to some other process?

**Comment by kirill-21** [comment]
> Is `hProcess` pointing to your current process or to some other process?

To some other process

**Comment by mraleph** [comment]
Then you need to use [`ReadProcessMemory`](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-readprocessmemory). You can't directly dereference the pointer because it originates from virtual address space of an another process.

**Comment by kirill-21** [comment]
> Then you need to use [`ReadProcessMemory`](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-readprocessmemory). You can't directly dereference the pointer because it originates from virtual address space of an another process.

I have an issue with RPM - it does not work for some reason: https://github.com/timsneath/win32/discussions/215. And i cannot find out the problem because GetLastError does not retrieve latest winapi error

**Comment by dcharkes** [comment]
@kirill-21 we're tracking that in https://github.com/dart-lang/sdk/issues/38832.
